### ISSUE TITLE
Compile error with testSwap.sol

### ISSUE THREAD

**Issue by daron4ever** [UV-Labs/Tutorials#6]
I got an "Unused local variable" compile error with the following snippet.

```
uint256[] memory amountsReceived = IUniswapV2Router(UNISWAP_V2_ROUTER).swapExactTokensForTokens(
            amountsExpected[0],
            (amountsExpected[1]*990)/1000, // accpeting a slippage of 1%
            path,
            _to,
            _deadline
        );
```

**Comment by amateur-dev** [comment]
Thanks for highlighting @daron4ever ; I have made an appropriate change so that you do not face that warning any more.  Let me know if this works out or if you have any more issue

**Comment by daron4ever** [comment]
> Thanks for highlighting @daron4ever ; I have made an appropriate change so that you do not face that warning any more. Let me know if this works out or if you have any more issue

Thanks. I deployed contract successfully. Now, I have another issue after this. I tried both mainnet or ropsten and I got same error and failed tx when I transact swap.
```
Gas estimation errored with the following message (see below). The transaction execution will likely fail. Do you want to force sending?
execution reverted
```

**Comment by amateur-dev** [comment]
Let me check @daron4ever

**Comment by amateur-dev** [comment]
@daron4ever 
(1) DO NOT TRY on MAINNET please; no point wasting any gas.
(2) On either of the nets, are you running the sample-test.js file on either of the networks? 
(3) Did you give all the approvals to the contract deployed?

**Comment by daron4ever** [comment]
> @daron4ever
> (1) DO NOT TRY on MAINNET please; no point wasting any gas.
> (2) On either of the nets, are you running the sample-test.js file on either of the networks?
> (3) Did you give all the approvals to the contract deployed?

Oh~ I forgot the approval. Thanks. it is working like a charm.
